version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: go get github.com/mattn/goveralls
      - run:
          name: Run unit tests
          command: |
            go get ./...
            go test -race -covermode=atomic -coverprofile=cover.out -v -tags test
            goveralls -coverprofile=cover.out -service=circle-ci
